Repository mwpenny/portal64-still-alive, pull requests merged in 2024-04, with the labels that each got.

#55 chamber 15
  Makefile
  assets/sound/vo/aperture_ai/10_part1_entry-1.sox
  assets/sound/vo/aperture_ai/10_part1_entry-2.sox
  assets/sound/vo/aperture_ai/10_part1_entry-3.sox
  assets/sound/vo/aperture_ai/10_part1_success-1.sox
  assets/test_chambers/test_chamber_10/test_chamber_10.blend
  assets/test_chambers/test_chamber_10/test_chamber_10.yaml
  src/levels/levels.c
  src/menu/new_game_menu.c
Labels: game content

#50 Snap grab rotations to cube normals
  src/player/player.c
  src/player/player.h
  src/scene/scene.c
Labels: enhancement

#57 Tweak y offset minimum limit to match original game (and due to issue #52)
  src/player/player.c
Labels: bug

#56 Add collision for fizzler frames
  src/scene/fizzler.c
  src/scene/fizzler.h
Labels: enhancement

#47 Use newlib instead of libnustd.
  Dockerfile
  Makefile
  documentation/manual_setup.md
  documentation/n64_library_usage.md
  src/math/mathf.h
  tools/setup.sh
Labels: building

#58 Grab rotation flags
  src/player/grab_rotation.c
  src/player/grab_rotation.h
  src/player/player.c
Labels: enhancement
