Repository mwpenny/portal64-still-alive, pull requests merged in 2024-03, with the labels that each got.

#15 Chamber14 trapped check
  assets/test_chambers/test_chamber_09/test_chamber_09.blend
  assets/test_chambers/test_chamber_09/test_chamber_09.yaml
  src/scene/button.c
  src/scene/button.h
Labels: enhancement, game content

#29 Serialize / deserialize detached security cameras in savegames
  src/savefile/scene_serialize.c
  src/scene/security_camera.c
  src/scene/security_camera.h
Labels: bug

#32 Dont fire portal with grabbed object or from pause menu
  src/player/player.c
  src/player/player.h
  src/scene/scene.c
  src/scene/scene.h
Labels: bug

#34 Throw direction fix when grabbing through portal
  src/player/player.c
  src/player/player.h
Labels: bug

#36 Encapsulate looking up a decorId from CollisionObjects
  src/decor/decor_object_list.c
  src/decor/decor_object_list.h
  src/scene/fizzler.c
  src/scene/trigger_listener.c
Labels: enhancement

#35 Keep grabbed objects in front of player & savegame grab through portals fix
  src/player/player.c
  src/savefile/scene_serialize.c
Labels: enhancement

#45 Confirm with player before leaving current game
  src/menu/confirmation_dialog.c
  src/menu/confirmation_dialog.h
  src/menu/game_menu.c
  src/menu/game_menu.h
  src/menu/load_game.c
  src/menu/new_game_menu.c
  src/menu/new_game_menu.h
  src/menu/savefile_list.c
  src/menu/savefile_list.h
  src/scene/scene.c
  src/scene/scene.h
  tools/level_scripts/subtitle_generate.py
Labels: enhancement

#43 Apply blender object scale to fizzlers
  src/scene/fizzler.c
  tools/level_scripts/entities.lua
Labels: enhancement, game content

#46 Use floorf defined in mathf.c instead of the C standard library floor function.
  src/scene/clock.c
Labels: refactoring

#49 Valve intro video: try to load a MOV file if the BIK file doesn't exist.
  Makefile
Labels: building
