Repository mwpenny/portal64-still-alive, pull requests merged in 2025-08, with the labels that each got.

#129 Fix beam platform loop pitch
  src/scene/scene_animator.c
Labels: bug

#133 Fix for constantly playing woosh sound
  src/player/player.c
Labels: bug, enhancement

#130 Added zoom feature
  assets/fonts/dejavu_sans/dejavu_sans_0.json
  assets/fonts/dejavu_sans/dejavu_sans_0.png
  assets/fonts/dejavu_sans/dejavu_sans_all.json
  assets/fonts/dejavu_sans/font_characters.txt
  src/controls/controller_actions.c
  src/controls/controller_actions.h
  src/menu/controls.c
  src/player/player.c
  src/savefile/savefile.h
  src/scene/portal_gun.c
  src/scene/portal_gun.h
  src/scene/render_plan.h
  src/scene/scene.c
  src/scene/scene.h
  tools/text/generate_strings.py
Labels: enhancement

#132 Add ambient hum sound for signage
  assets/sound/CMakeLists.txt
  assets/sound/ambient/machines/fluorescent_hum_1.ins
  assets/sound/ambient/machines/fluorescent_hum_1.sox
  src/audio/clips.c
  src/audio/clips.h
  src/levels/cutscene_runner.c
  src/menu/main_menu.c
  src/scene/signage.c
  src/scene/signage.h
Labels: enhancement
